
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faPython,
  faJs,
  faPhp,
  faHtml5,
  faCss3Alt,
  faReact,
  faNodeJs,
  faBootstrap,
  faGitAlt,
  faJira,
  faTrello,
  faLinux,
  faApple,
  faWindows,
  faAws,
  faGoogle,
  faMicrosoft,
  faDocker,
  faJenkins,
  faFigma,
  faNpm,
  faYarn,
  faSlack,
  faConfluence,
  faBitbucket,
  faGithub,
  faGitlab,
  faJava,
  faSass,
  faLess,
  faVuejs,
  faAngular,
  faEmber,
  faGulp,
  faGrunt,
  faWordpress,
  faDrupal,
  faJoomla,
  faShopify,
  faMagento,
  faSquarespace,
  faWix,
  faWeebly,
  faWebflow,
  faDribbble,
  faBehance,
  faPinterest,
  faInstagram,
  faFacebook,
  faTwitter,
  faYoutube,
  faVimeo,
  faTiktok,
  faSnapchat,
  faDiscord,
  faSkype,
  faWhatsapp,
  faTelegram,
  faSignal,
  faLine,
  faWeixin,
  faQq,
  faVk,
  faOdnoklassniki,
  faReddit,
  faTumblr,
  faLinkedin,
  faXing,
  faRenren,
  faSinaWeibo,
  faMedium,
  faQuora,
  faStackOverflow,
faProductHunt,
  faHackerNews,
  faGlide,
  faPiedPiper,
  faAlgolia,
  faAdn,
  faApper,
  faBuromobelexperte,
  faCentercode,
  faCloudflare,
  faCpanel,
  faDashcube,
  faDeploydog,
  faDigitalOcean,
  faEvernote,
  faExpeditedssl,
  faFly,
  faFreebsd,
  faFulcrum,
  faGofore,
  faGoodreads,
  faGoogleDrive,
  faGooglePlay,
  faGratipay,
  faGrav,
  faHeroku,
  faHotjar,
  faHubspot,
  faIntercom,
  faItchIo,
  faJsfiddle,
  faKeybase,
  faKickstarter,
  faLaravel,
  faLastfm,
  faMailchimp,
  faMastodon,
  faMeetup,
  faMixcloud,
  faPage4,
  faPatreon,
  faPaypal,
  faPeriscope,
  faPiedPiperAlt,
  faPiedPiperHat,
  faPiedPiperPp,
  faRebel,
  faRedhat,
  faResolving,
  faRev,
  faRocketchat,
  faScribd,
  faSearchengin,
  faSellcast,
  faServicestack,
  faShirtsinbulk,
  faSimplybuilt,
  faSistrix,
  faSlideshare,
  faSoundcloud,
  faSpeakerDeck,
  faSpotify,
  faStaylinked,
  faSteam,
  faStickerMule,
  faStripe,
  faStudiovinari,
  faSupple,
  faSymfony,
  faTeamspeak,
  faThemeco,
  faThemeisle,
  faTradeFederation,
  faTripadvisor,
  faTwitch,
  faTypo3,
  faUber,
  faUbuntu,
  faUikit,
  faUniregistry,
  faUntappd,
  faUsb,
  faUssunnah,
  faViacoin,
  faViadeo,
  faViber,
  faVine,
  faVnv,
  faWpexplorer,
  faYahoo,
  faYandex,
  faYelp,
  faYoast,
  faZhihu,
  faKaggle
} from "@fortawesome/free-brands-svg-icons";
import {
  faDatabase,
  faCode,
  faBrain,
  faServer,
  faTerminal,
  faFileCode,
  faWind,
  faBook,
  faCloud,
  faCodeBranch,
  faChartSimple,
  faGear,
  faTable,
  faCalculator,
  faChartBar,
  faChartPie,
  faCameraRetro,
  faBolt
} from "@fortawesome/free-solid-svg-icons";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";

interface TechIconProps {
  technology: string;
  className?: string;
}

const iconMap: Record<string, IconDefinition> = {
  // Languages
  python: faPython,
  javascript: faJs,
  c: faCode,
  "c++": faCode,
  php: faPhp,
  html: faHtml5,
  css: faCss3Alt,
  sql: faDatabase,

  // AI/ML
  langchain: faBrain,
  langgraph: faCodeBranch,
  pyspark: faChartSimple,
  "scikit-learn": faGear,
  pandas: faTable,
  numpy: faCalculator,
  matplotlib: faChartBar,
  seaborn: faChartPie,
  tensorflow: faBrain,
  opencv: faCameraRetro,
  "google gemini api": faGoogle,
  "huggingface embeddings": faBrain,

  // Frontend & Web
  react: faReact,
  "next.js": faCode,
  "node.js": faNodeJs,
  "express.js": faServer,
  bootstrap: faBootstrap,
  "tailwind css": faWind,
  streamlit: faWind,
  "beautifulsoup": faFileCode,
  selenium: faCode,

  // Databases
  mysql: faDatabase,
  mongodb: faDatabase,
  postgresql: faDatabase,
  chromadb: faDatabase,

  // Tools
  git: faCodeBranch,
  "vs code": faCode,
  pycharm: faCode,
  "jupyter notebook": faBook,
  postman: faServer,
  vercel: faCloud,
  kaggle: faKaggle,
  "google colab": faGoogle,
  databricks: faDatabase,
  "clerk authentication": faBolt,
  "firebase studio": faCode,
  notebooklm: faBook,
  replit: faCode,
  dotenv: faTerminal,
  "restful apis": faServer,
  "jwt": faTerminal,
  "web scraping": faCode,
  "agile": faTerminal,
  "rest apis": faServer,
  "machine learning": faBrain,
  "django": faCode,
  "data analysis": faChartSimple,
  "generative ai": faBrain,
  "agents": faBrain,
  "agentic ai": faBrain,
  docker: faDocker,
};

export function TechIcon({ technology, className }: TechIconProps) {
  const icon = iconMap[technology.toLowerCase()] || faFileCode;
  return <FontAwesomeIcon icon={icon} className={className} />;
}
