
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faPython,
  faJs,
  faPhp,
  faHtml5,
  faCss3Alt,
  faReact,
  faNodeJs,
  faBootstrap,
  faGitAlt,
  faJira,
  faTrello,
  faLinux,
  faApple,
  faWindows,
  faAws,
  faGoogle,
  faMicrosoft,
  faDocker,
  faJenkins,
  faFigma,
  faNpm,
  faYarn,
  faSlack,
  faConfluence,
  faBitbucket,
  faGithub,
  faGitlab,
  faJava,
  faSass,
  faLess,
  faVuejs,
  faAngular,
  faEmber,
  faGulp,
  faGrunt,
  faWordpress,
  faDrupal,
  faJoomla,
  faShopify,
  faMagento,
  faSquarespace,
  faWix,
  faWeebly,
  faWebflow,
  faDribbble,
  faBehance,
  faPinterest,
  faInstagram,
  faFacebook,
  faTwitter,
  faYoutube,
  faVimeo,
  faTiktok,
  faSnapchat,
  faDiscord,
  faSkype,
  faWhatsapp,
  faTelegram,
  faSignal,
  faLine,
  faWeixin,
  faQq,
  faVk,
  faOdnoklassniki,
  faReddit,
  faTumblr,
  faLinkedin,
  faXing,
  faRenren,
  faSinaWeibo,
  faMedium,
  faQuora,
  faStackOverflow,
  faProductHunt,
  faHackerNews,
  faGlide,
  faPiedPiper,
  faAlgolia,
  faAdn,
  faApper,
  faBuromobelexperte,
  faCentercode,
  faCloudflare,
  faCpanel,
  faDashcube,
  faDeploydog,
  faDigitalOcean,
  faDockerhub,
faEvernote,
faExpeditedssl,
faFly,
faFreebsd,
faFulcrum,
faGofore,
faGoodreads,
faGoogleDrive,
faGooglePlay,
faGratipay,
faGrav,
faHeroku,
faHotjar,
faHubspot,
faIntercom,
faItchIo,
faJsfiddle,
faKeybase,
faKickstarter,
faLaravel,
faLastfm,
faMailchimp,
faMastodon,
faMeetup,
faMixcloud,
faPage4,
faPatreon,
faPaypal,
faPeriscope,
faPiedPiperAlt,
faPiedPiperHat,
faPiedPiperPp,
faQqchat,
faQuip,
faRebel,
faRedhat,
faResolving,
faRev,
faRocketchat,
faScribd,
faSearchengin,
faSellcast,
faServicestack,
faShirtsinbulk,
faSimplybuilt,
faSistrix,
faSlideshare,
faSoundcloud,
faSpeakerDeck,
faSpotify,
faStaylinked,
faSteam,
faStickerMule,
faStripe,
faStudiovinari,
faSupple,
faSymfony,
faTeamspeak,
faThemeco,
faThemeisle,
faTradeFederation,
faTripadvisor,
faTwitch,
faTypo3,
faUber,
faUbuntu,
faUikit,
faUniregistry,
faUntappd,
faUsb,
faUssunnah,
faViacoin,
faViadeo,
faViber,
faVine,
faVnv,
faVuejsSquare,
faWpexplorer,
faYahoo,
faYandex,
faYelp,
faYoast,
faZhihu,
faKaggle
} from "@fortawesome/free-brands-svg-icons";
import {
  faDatabase,
  faCode,
  faBrain,
  faServer,
  faTerminal,
  faFileCode,
  faWind,
  faBook,
  faCloud,
  faCodeBranch,
} from "@fortawesome/free-solid-svg-icons";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";

interface TechIconProps {
  technology: string;
  className?: string;
}

const iconMap: Record<string, IconDefinition> = {
  // Languages
  python: faPython,
  javascript: faJs,
  c: faCode,
  "c++": faCode,
  php: faPhp,
  html: faHtml5,
  css: faCss3Alt,
  sql: faDatabase,

  // AI/ML
  langchain: faBrain,
  langgraph: faBrain,
  "scikit-learn": faBrain,
  pandas: faBook,
  numpy: faBook,
  matplotlib: faBrain,
  seaborn: faBrain,
  tensorflow: faBrain,
  opencv: faBrain,
  pyspark: faBrain,

  // Frontend & Web
  react: faReact,
  "next.js": faCode,
  "node.js": faNodeJs,
  "express.js": faServer,
  bootstrap: faBootstrap,
  "tailwind css": faWind,

  // Databases
  mysql: faDatabase,
  mongodb: faDatabase,
  postgresql: faDatabase,

  // Tools
  git: faCodeBranch,
  "vs code": faTerminal,
  pycharm: faTerminal,
  "jupyter notebook": faBook,
  postman: faTerminal,
  vercel: faCloud,
  kaggle: faKaggle,
  "google colab": faGoogle,
  databricks: faDatabase,
  "clerk authentication": faTerminal,
  "firebase studio": faCode,
  notebooklm: faBook,
  replit: faTerminal,
};

export function TechIcon({ technology, className }: TechIconProps) {
  const icon = iconMap[technology.toLowerCase()] || faFileCode;
  return <FontAwesomeIcon icon={icon} className={className} />;
}
